stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw/Salary_dataset.csv
    - src/preprocess.py
    outs:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
  train:
    cmd: python src/train.py
    deps:
    - data/processed/X_train.csv
    - data/processed/y_train.csv
    - params.yaml
    - src/train.py
    outs:
    - models/model.pkl
  evaluate:
    cmd: python src/evaluate.py
    deps:
      - data/processed/X_test.csv
      - data/processed/y_test.csv
      - models/model.pkl
      - src/evaluate.py
    metrics:
      - metrics.json:
          cache: false
    outs: []